### ISSUE TITLE
[Feature] Reconnect for connection error

### ISSUE THREAD

**Issue by jim3ma** [jim3ma/gota#5]
Implement a path reconnection after error/close. At time, when one path goes off-line then client never tryes to reopen it. Will be very interesting to try to reconnect inmediatly after the connection is closed, and if an error is comming, then wait some delay and retry.

Split from #4

**Comment by lars18th** [comment]
Hi,

I think this has sense only in the CLIENT side, as the client initiates the TCP connection over each path.

So, I suggest this enhancement in "config.client.yml":
```
# default for server, did not change it
mode: client

# log level: info debug warn error fatal panic
log: debug

# tunnel authenticate credential
auth:
  username: gota
  password: gota

# local listen address with port
listen: 127.0.0.1:12363

fastopen: true

# Gota server addresses with port
tunnel:
  - remote: 127.0.0.1:12333 reconn=60 # connect server directly
  - remote: 127.0.0.1:12336 reconn=30
  #  proxy: http://gota:gota@127.0.0.1:3128 reconn=0 # connect server using proxy, currently Gota support http/https/socks5 proxy
```

Here "reconn" is a path based parameter. When the socket closes then wait x seconds before try to reconnect. Value "0" indicates "no wait". And if you think it has sense, then consider also "-1" for "no reconnect".

You agree?
Regards.
